### ISSUE TITLE
E3 - Conexão do Heroku com GitHub para deploy automático

### ISSUE THREAD

**Issue by JP-Colafati** [wandsu/burnhop-server#12]

**Comment by wandsu** [comment]
- [x] Conectar heroku ao repositório

- [x] Configurar o deploy automático

**Comment by wandsu** [comment]
Conectado o Heroku com o repositório do projeto.
Realizando os testes para detectar possíveis mudanças no comportamento da aplicação.

**Comment by wandsu** [comment]
Validado o funcionamento do Deploy automático.
